# Copyright (c) 2025 Yusuke KITAGAWA (tonosama_kaeru@icloud.com)

TAG_SPEC: list[dict[str, object]] = [
    # ===================== Metadata =====================
    {"tag": "html"},
    {"tag": "head"},
    {"tag": "title"},
    {"tag": "base"},
    {"tag": "meta"},
    {"tag": "style"},
    {"tag": "body"},
    # ===================== Sectioning =====================
    {"tag": "article"},
    {"tag": "section"},
    {"tag": "nav"},
    {"tag": "aside"},
    {"tag": "h1"},
    {"tag": "h2"},
    {"tag": "h3"},
    {"tag": "h4"},
    {"tag": "h5"},
    {"tag": "h6"},
    {"tag": "header"},
    {"tag": "footer"},
    {"tag": "address"},
    # ===================== Grouping =====================
    {"tag": "p"},
    {"tag": "hr"},
    {"tag": "pre"},
    {"tag": "blockquote"},
    {"tag": "ol", "restricted_bool": ["reversed"]},
    {"tag": "ul"},
    {"tag": "menu"},
    {"tag": "li"},
    {"tag": "dl"},
    {"tag": "dt"},
    {"tag": "dd"},
    {"tag": "figure"},
    {"tag": "figcaption"},
    {"tag": "main"},
    {"tag": "div"},
    # ===================== Text-level =====================
    {"tag": "em"},
    {"tag": "strong"},
    {"tag": "small"},
    {"tag": "s"},
    {"tag": "cite"},
    {"tag": "q"},
    {"tag": "dfn"},
    {"tag": "abbr"},
    {"tag": "ruby"},
    {"tag": "rt"},
    {"tag": "rp"},
    {"tag": "data"},
    {"tag": "time"},
    {"tag": "code"},
    {"tag": "var"},
    {"tag": "samp"},
    {"tag": "kbd"},
    {"tag": "sub"},
    {"tag": "sup"},
    {"tag": "i"},
    {"tag": "b"},
    {"tag": "u"},
    {"tag": "mark"},
    {"tag": "bdi"},
    {"tag": "bdo"},
    {"tag": "span"},
    {"tag": "br"},
    {"tag": "wbr"},
    # ===================== Edits =====================
    {"tag": "ins"},
    {"tag": "del"},
    # ===================== Embedded content =====================
    {"tag": "picture"},
    {"tag": "source"},
    {
        "tag": "img",
        "restricted_literal": {
            "loading": ["lazy", "eager"],
            "decoding": ["sync", "async", "auto"],
            "fetchpriority": ["high", "low", "auto"],
        },
        "restricted_bool": ["ismap"],
    },
    {"tag": "iframe"},
    {"tag": "embed"},
    {"tag": "object"},
    {"tag": "param"},
    {
        "tag": "video",
        "restricted_bool": ["autoplay", "controls", "loop", "muted"],
    },
    {
        "tag": "audio",
        "restricted_bool": ["autoplay", "controls", "loop", "muted"],
    },
    {"tag": "track", "restricted_bool": ["default"]},
    {"tag": "map"},
    {"tag": "area"},
    # ===================== Tables =====================
    {"tag": "table"},
    {"tag": "caption"},
    {"tag": "colgroup"},
    {"tag": "col"},
    {"tag": "thead"},
    {"tag": "tbody"},
    {"tag": "tfoot"},
    {"tag": "tr"},
    {"tag": "th"},
    {"tag": "td"},
    # ===================== Forms =====================
    {
        "tag": "form",
        "restricted_literal": {
            "method": ["get", "post"],
            "enctype": [
                "application/x-www-form-urlencoded",
                "multipart/form-data",
                "text/plain",
            ],
        },
        "restricted_bool": ["novalidate"],
    },
    {"tag": "label"},
    {
        "tag": "select",
        "restricted_bool": ["autofocus", "disabled", "multiple", "required"],
    },
    {"tag": "datalist"},
    {"tag": "optgroup", "restricted_bool": ["disabled"]},
    {
        "tag": "option",
        "restricted_bool": ["disabled", "selected"],
    },
    {
        "tag": "textarea",
        "restricted_bool": ["autofocus", "disabled", "readonly", "required"],
    },
    {"tag": "output"},
    {"tag": "progress"},
    {"tag": "meter"},
    {"tag": "fieldset", "restricted_bool": ["disabled"]},
    {"tag": "legend"},
    {
        "tag": "input",
        "restricted_literal": {
            "type": [
                "text",
                "password",
                "number",
                "email",
                "checkbox",
                "radio",
                "date",
                "datetime-local",
                "file",
                "hidden",
                "image",
                "month",
                "range",
                "reset",
                "search",
                "submit",
                "tel",
                "time",
                "url",
                "week",
                "color",
            ],
        },
        "restricted_bool": [
            "disabled",
            "required",
            "checked",
            "multiple",
            "readonly",
            "autofocus",
        ],
    },
    {
        "tag": "button",
        "restricted_literal": {"type": ["button", "submit", "reset"]},
        "restricted_bool": ["disabled", "formnovalidate"],
    },
    {
        "tag": "a",
        "restricted_literal": {
            "target": ["_self", "_blank", "_parent", "_top"],
        },
    },
    # ===================== Interactive =====================
    {"tag": "details", "restricted_bool": ["open"]},
    {"tag": "summary"},
    {"tag": "dialog", "restricted_bool": ["open"]},
    # ===================== Scripting =====================
    {
        "tag": "script",
        "restricted_literal": {"type": ["module", "text/javascript"]},
        "restricted_bool": ["async", "defer", "nomodule"],
    },
    {"tag": "noscript"},
    {"tag": "template"},
    {"tag": "slot"},
    {"tag": "canvas"},
    # ===================== Links =====================
    {
        "tag": "link",
        "restricted_literal": {
            "rel": [
                "stylesheet",
                "icon",
                "preload",
                "prefetch",
                "modulepreload",
                "manifest",
            ],
        },
        "restricted_bool": ["disabled"],
    },
]
