# This file is auto-generated by zen_html._generator.
# Do not edit this file directly; update _tag_spec.py and rerun the generator.
# mypy: disable-error-code=empty-body
# mypy: disable-error-code=misc
from typing import Literal

from ._base import Children, ClassAttr, PropVal, _HBase, html_tag


class H(_HBase):
    @html_tag
    def html(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        lang: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def head(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def title(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def base(
        *,
        href: str | None = None,
        target: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def meta(
        *,
        charset: str | None = None,
        http_equiv: str | None = None,
        name: str | None = None,
        content: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def style(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        media: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def body(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def article(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def section(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def nav(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def aside(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def h1(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def h2(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def h3(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def h4(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def h5(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def h6(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def header(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def footer(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def address(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def p(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def hr(
        *,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def pre(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def blockquote(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        cite: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def ol(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        reversed: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def ul(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def menu(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def li(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def dl(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def dt(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def dd(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def figure(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def figcaption(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def main(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def div(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def em(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def strong(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def small(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def s(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def cite(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        cite: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def q(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        cite: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def dfn(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def abbr(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def ruby(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def rt(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def rp(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def data(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        value: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def time(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        datetime: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def code(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def var(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def samp(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def kbd(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def sub(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def sup(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def i(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def b(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def u(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def mark(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def bdi(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def bdo(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def span(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def br(
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def wbr(
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def ins(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        cite: str | None = None,
        datetime: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def del_(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        cite: str | None = None,
        datetime: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def picture(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def source(
        *,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str | None = None,
        type: str | None = None,
        media: str | None = None,
        sizes: str | None = None,
        srcset: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def img(
        *,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str,
        alt: str | None = None,
        loading: Literal["lazy", "eager"] | None = None,
        decoding: Literal["sync", "async", "auto"] | None = None,
        fetchpriority: Literal["high", "low", "auto"] | None = None,
        ismap: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def iframe(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str | None = None,
        title: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def embed(
        *,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str | None = None,
        type: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def object(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        data: str | None = None,
        type: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def param(
        *,
        name: str | None = None,
        value: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def video(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str,
        poster: str | None = None,
        autoplay: bool | None = None,
        controls: bool | None = None,
        loop: bool | None = None,
        muted: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def audio(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str,
        autoplay: bool | None = None,
        controls: bool | None = None,
        loop: bool | None = None,
        muted: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def track(
        *,
        src: str | None = None,
        kind: Literal["subtitles", "captions", "descriptions", "chapters", "metadata"],
        srclang: str | None = None,
        label: str | None = None,
        default: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def map(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def area(
        *,
        alt: str | None = None,
        coords: str | None = None,
        shape: str | None = None,
        href: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def table(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def caption(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def colgroup(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def col(
        *,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def thead(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def tbody(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def tfoot(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def tr(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def th(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def td(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def form(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        action: str | None = None,
        method: Literal["get", "post"] | None = None,
        enctype: (
            Literal["application/x-www-form-urlencoded", "multipart/form-data", "text/plain"] | None
        ) = None,
        target: str | None = None,
        novalidate: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def label(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        for_: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def select(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        form: str | None = None,
        autofocus: bool | None = None,
        disabled: bool | None = None,
        multiple: bool | None = None,
        required: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def datalist(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def optgroup(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        label: str | None = None,
        disabled: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def option(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        label: str | None = None,
        value: str | None = None,
        disabled: bool | None = None,
        selected: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def textarea(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        rows: str | None = None,
        cols: str | None = None,
        autofocus: bool | None = None,
        disabled: bool | None = None,
        readonly: bool | None = None,
        required: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def output(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        for_: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def progress(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        value: str | None = None,
        max: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def meter(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        value: str | None = None,
        min: str | None = None,
        max: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def fieldset(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        disabled: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def legend(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def input(
        *,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        type: (
            Literal[
                "text",
                "password",
                "number",
                "email",
                "checkbox",
                "radio",
                "date",
                "datetime-local",
                "file",
                "hidden",
                "image",
                "month",
                "range",
                "reset",
                "search",
                "submit",
                "tel",
                "time",
                "url",
                "week",
                "color",
            ]
            | None
        ) = None,
        value: str | None = None,
        placeholder: str | None = None,
        min: str | None = None,
        max: str | None = None,
        step: str | None = None,
        pattern: str | None = None,
        accept: str | None = None,
        autocomplete: Literal["off", "on"] | None = None,
        disabled: bool | None = None,
        required: bool | None = None,
        checked: bool | None = None,
        multiple: bool | None = None,
        readonly: bool | None = None,
        autofocus: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def button(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        value: str | None = None,
        type: Literal["button", "submit", "reset"] | None = None,
        disabled: bool | None = None,
        formnovalidate: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def a(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        href: str | None = None,
        target: Literal["_self", "_blank", "_parent", "_top"] | None = None,
        rel: str | None = None,
        download: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def details(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        open: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def summary(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def dialog(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        open: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def script(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        src: str | None = None,
        type: Literal["module", "text/javascript"] | None = None,
        async_: bool | None = None,
        defer: bool | None = None,
        nomodule: bool | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def noscript(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def template(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def slot(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def canvas(
        *_children: Children,
        children: Children | None = None,
        class_: ClassAttr = None,
        id: str | None = None,
        name: str | None = None,
        width: str | None = None,
        height: str | None = None,
        **props: PropVal,
    ) -> "H": ...

    @html_tag
    def link(
        *,
        href: str,
        rel: Literal["stylesheet", "icon", "preload", "prefetch", "modulepreload", "manifest"] | None = None,
        as_: str | None = None,
        type: str | None = None,
        disabled: bool | None = None,
        media: str | None = None,
        sizes: str | None = None,
        **props: PropVal,
    ) -> "H": ...
